- name: Jest Annotations & Coverage
  # You may pin to the exact commit or the version.
  # uses: mattallty/jest-github-action@43bbcd073fa43a927322f188220b6592acae003b
  uses: mattallty/jest-github-action@v1.0.3
  with:
    # The test command to run
    test-command: # optional, default is npm test
    # Subdirectory to run tests in
    working-directory: # optional, default is 
    # Comment PRs with code coverage
    coverage-comment: # optional, default is true
    # Only run tests on changed files (over base branch)
    changes-only: # optional, default is false
